export enum routes {
  //auth
  ONBOARD = 'ONBOARD',
  SIGN_IN = 'SIGN_IN',
  CREATE_ACCOUNT = 'CREATE_ACCOUNT',
  LOBBY = 'LOBBY',
  UPDATE_PROFILE = 'UPDATE_PROFILE',

  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
  SEND_OTP = 'SEND_OTP',
  CREATE_NEW_PASSWORD = 'CREATE_NEW_PASSWORD',

  BOTTOM_TAB = 'bottom_tab',
  HOME = 'HOME',

  FORUM = 'FORUM',
  APP_NAVIGATOR = 'APP_NAVIGATOR',

  PROFILE = 'PROFILE',

  HISTORY = 'HISTORY',



}
